name: CI - Train Model

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.10"

      - name: Install pipenv
        run: pip install --upgrade pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run pytest --maxfail=1 -v

      - name: Train model
        run: pipenv run python src/train.py
